/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aldrin.rl.gui;

import com.aldrin.rl.RememberLogin2;
import com.aldrin.rl.dao.impl.UserDAOImpl;
import com.aldrin.rl.gui.dialog.JDialogUser;
import com.aldrin.rl.gui.panel.JPanelAnalytics;
import com.aldrin.rl.gui.panel.JPanelComments;
import com.aldrin.rl.gui.panel.JPanelContent;
import com.aldrin.rl.gui.panel.JPanelDashboard;
import com.aldrin.rl.gui.panel.JPanelSettings;
import com.aldrin.rl.model.User;
import com.aldrin.rl.util.LoginUser;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.util.prefs.Preferences;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JFrameApp extends javax.swing.JFrame {

//    Font fontSize16 = UIManager.getFont("h3.regular.font");
    LoginUser loginUser = new LoginUser();
    private static final String USERNAME_PREF_KEY = "username";
    private static final String PASSWORD_PREF_KEY = "password";
    Preferences preferences = Preferences.userNodeForPackage(RememberLogin2.class);

    private CardLayout cardLayout = new CardLayout();
    private JPanel cardsPanel = new JPanel(cardLayout);
    JPanelDashboard panelDashboard = new JPanelDashboard();
    JPanelContent panelContent = new JPanelContent();
    JPanelComments panelComments = new JPanelComments();
    JPanelAnalytics panelAnalytics = new JPanelAnalytics();
    JPanelSettings panelSettings = new JPanelSettings();

    /**
     * Creates new form JFrameApp
     */
    public JFrameApp() {
        initComponents();
//        Font newFont = fontSize16.deriveFont(16);
//        UIManager.put("defaultFont", newFont);
        FlatLaf.updateUI();
        FlatSVGIcon icon = new FlatSVGIcon("svg/calculator.svg", 24, 24);
        setIconImage(icon.getImage());
        setVisible(true);
        String storedUsername = preferences.get(USERNAME_PREF_KEY, null);
        String storedPassword = preferences.get(PASSWORD_PREF_KEY, null);
        jMenuItemLogout.setVisible(false);
        loginUser.setUser(null);

        saveLoginCredentials();

        cardsPanel.add(panelDashboard, "Dashboard");
        cardsPanel.add(panelContent, "Content");
        cardsPanel.add(panelComments, "Comments");
        cardsPanel.add(panelAnalytics, "Analytics");
        cardsPanel.add(panelSettings, "Settings");
        jPanel2.add(cardsPanel, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanelSideBarButtons = new javax.swing.JPanel();
        jButtonDashboard = new javax.swing.JButton();
        jButtonContent = new javax.swing.JButton();
        jButtonComments = new javax.swing.JButton();
        jButtonAnalytics = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabelPhoto = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuApp = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remember me Login App");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(160, 10));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(102, 102, 102)));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanelSideBarButtons.setOpaque(false);
        jPanelSideBarButtons.setPreferredSize(new java.awt.Dimension(10, 160));
        jPanelSideBarButtons.setLayout(new java.awt.GridLayout(0, 1));

        jButtonDashboard.setIcon(new FlatSVGIcon("svg/dashboard.svg",16,16));
        jButtonDashboard.setText("Dashboard");
        jButtonDashboard.setBorder(null);
        jButtonDashboard.setBorderPainted(false);
        jButtonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonDashboard.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDashboardActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonDashboard);

        jButtonContent.setIcon(new FlatSVGIcon("svg/content.svg",16,16));
        jButtonContent.setText("Content");
        jButtonContent.setBorder(null);
        jButtonContent.setBorderPainted(false);
        jButtonContent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonContent.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContentActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonContent);

        jButtonComments.setIcon(new FlatSVGIcon("svg/comments.svg",16,16));
        jButtonComments.setText("Comments");
        jButtonComments.setBorder(null);
        jButtonComments.setBorderPainted(false);
        jButtonComments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonComments.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommentsActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonComments);

        jButtonAnalytics.setIcon(new FlatSVGIcon("svg/analytics.svg",16,16));
        jButtonAnalytics.setText("Analytics");
        jButtonAnalytics.setBorder(null);
        jButtonAnalytics.setBorderPainted(false);
        jButtonAnalytics.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAnalytics.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalyticsActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonAnalytics);

        jButtonSettings.setIcon(new FlatSVGIcon("svg/settings.svg",16,16));
        jButtonSettings.setText("Settings");
        jButtonSettings.setBorder(null);
        jButtonSettings.setBorderPainted(false);
        jButtonSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSettings.setMargin(new java.awt.Insets(2, 5, 2, 0));
        jButtonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsActionPerformed(evt);
            }
        });
        jPanelSideBarButtons.add(jButtonSettings);

        jPanel4.add(jPanelSideBarButtons, java.awt.BorderLayout.NORTH);

        jPanel7.setOpaque(false);
        jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setFocusable(false);
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 190));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout());

        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/images/photo.png"));
        jLabelPhoto.setIcon(new ImageIcon(getCircleImage(imageIcon.getImage(), 140, 140)));
        jLabelPhoto.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jLabelPhoto, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel9.setOpaque(false);
        jPanel5.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(10, 40));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel13.setOpaque(false);

        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel13.add(jLabelUser);

        jPanel10.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel14.setOpaque(false);
        jPanel10.add(jPanel14, java.awt.BorderLayout.WEST);
        jPanel10.add(jPanel15, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel10, java.awt.BorderLayout.SOUTH);

        jPanel11.setOpaque(false);
        jPanel5.add(jPanel11, java.awt.BorderLayout.EAST);

        jPanel12.setOpaque(false);
        jPanel5.add(jPanel12, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuApp.setText("App");

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuApp.add(jMenuItemLogin);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuApp.add(jMenuItemLogout);
        jMenuApp.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuApp.add(jMenuItem2);

        jMenuBar1.add(jMenuApp);

        jMenuSettings.setText("Settings");

        jMenuItem3.setText("User");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItem3);

        jMenuBar1.add(jMenuSettings);

        jMenu2.setText("Help");

        jMenuItem1.setText("About");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1137, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        JDialogLogin login = new JDialogLogin(this, true);
        login.setVisible(true);
        loginUser();
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        jPanelSideBarButtons.setVisible(false);
        cardsPanel.setVisible(false);
        clearLoginCredentials();
        loginUser.setUser(null);
        loginUser();
        JDialogLogin login = new JDialogLogin(this, true);
        login.setVisible(true);
        loginUser();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JDialogUser user = new JDialogUser(this, true);
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
        cardLayout.show(cardsPanel, "Settings");
    }//GEN-LAST:event_jButtonSettingsActionPerformed

    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed

        cardLayout.show(cardsPanel, "Dashboard");

    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContentActionPerformed
        cardLayout.show(cardsPanel, "Content");
    }//GEN-LAST:event_jButtonContentActionPerformed

    private void jButtonCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommentsActionPerformed
        cardLayout.show(cardsPanel, "Comments");
    }//GEN-LAST:event_jButtonCommentsActionPerformed

    private void jButtonAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalyticsActionPerformed
        cardLayout.show(cardsPanel, "Analytics");
    }//GEN-LAST:event_jButtonAnalyticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalytics;
    private javax.swing.JButton jButtonComments;
    private javax.swing.JButton jButtonContent;
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuApp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelSideBarButtons;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
private void loginUser() {
        if (loginUser.getUser() != null) {
//            login 
            cardsPanel.setVisible(true);
            cardsPanel.add(panelDashboard, "Dashboard");
            cardsPanel.add(panelContent, "Content");
            cardsPanel.add(panelComments, "Comments");
            cardsPanel.add(panelAnalytics, "Analytics");
            cardsPanel.add(panelSettings, "Settings");
            jPanel2.add(cardsPanel, BorderLayout.CENTER);
            jMenuApp.setText(loginUser.getUser().getSurname() + ", " + loginUser.getUser().getFirstname());
            jMenuItemLogout.setVisible(true);
            jMenuItemLogin.setVisible(false);
            jLabelUser.setText(loginUser.getUser().getSurname() + ", " + loginUser.getUser().getFirstname());
            jPanelSideBarButtons.setVisible(true);
            displayPicture(loginUser.getUser());
            if (loginUser.getUser().getRole().getRole().equals("ADMIN")) {
                jMenuSettings.setVisible(true);
                jButtonSettings.setEnabled(true);
            } else if (loginUser.getUser().getRole().getRole().equals("USER")) {
                jMenuSettings.setVisible(false);
                jButtonSettings.setEnabled(false);
            }
        } else {
//            logout
            jMenuApp.setText("App");
            jLabelPhoto.setIcon(null);
            jLabelUser.setText("");
            jMenuItemLogout.setVisible(false);
            jMenuSettings.setVisible(false);
            jMenuItemLogin.setVisible(true);
            jPanelSideBarButtons.setVisible(false);

        }

    }

    private void clearLoginCredentials() {
        try {
            preferences.remove(USERNAME_PREF_KEY);
            preferences.remove(PASSWORD_PREF_KEY);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
//

    private void saveLoginCredentials() {
        try {
            UserDAOImpl userDAOImpl = new UserDAOImpl();
            User user = new User();
            String storedUsername = preferences.get(USERNAME_PREF_KEY, null);
            String storedPassword = preferences.get(PASSWORD_PREF_KEY, null);
            user.setUsername(storedUsername);
            user.setPassword(storedPassword);
            if (userDAOImpl.loginUser(user) != null) {
                LoginUser logInUser = new LoginUser();
                user = userDAOImpl.loginUser(user);
                logInUser.setUser(user);
                loginUser();
                displayPicture(logInUser.getUser());
                // login for jdialog
            } else {
                loginUser();
                JDialogLogin logIn = new JDialogLogin(this, true);
                logIn.setVisible(true);
                loginUser();
            }
            addPanels();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    int IMG_WIDTH = 140;
    int IMG_HEIGHT = 140;

    private void displayPicture(User user) {
        try {
            byte[] imageData = user.getPhoto();
            ImageIcon imageIcon = new ImageIcon(imageData);
            jLabelPhoto.setIcon(new ImageIcon(getCircleImage(imageIcon.getImage(), 140, 140)));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private Image getCircleImage(Image img, int width, int height) {
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = image.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        Ellipse2D.Double circle = new Ellipse2D.Double(0, 0, width, height);
        g2.setClip(circle);
        g2.drawImage(img, 0, 0, width, height, null);
        g2.dispose();
        return image;
    }

    private void addPanels() {
        cardsPanel = new JPanel(cardLayout);
        cardsPanel.add(panelDashboard, "Dashboard");
        cardsPanel.add(panelContent, "Content");
    }

}
